# car feedback data. 
Header header         # standard ROS message header
uint64 frame_id_num  
float32 wheel_speed_fl
float32 wheel_speed_fr
float32 wheel_speed_rl
float32 wheel_speed_rr
float32 motor_command_speed_rl
float32 motor_command_speed_rr
float32 motor_return_speed_rl
float32 motor_return_speed_rr
float32 motor_command_torq_rl
float32 motor_command_torq_rr
float32 motor_return_torq_rl
float32 motor_return_torq_rr
