# message of Asensing perception result.It is INS data. 
Header header         # standard ROS message header
uint64 frame_id_num  
float32 sum_compute_time
float32 control_compute_time
float32 boundary_detector_compute_time
float32 line_detector_compute_time
float32 skidpad_detector_compute_time
float32 lidar_detection_compute_time
float32 camera_detection_compute_time
float32 fusion_detection_compute_time
float32 time2
float32 time3
float32 time4
float32 time5
float32 time6
float32 time7
float32 time8
float32 time9

